apiVersion: v1
kind: Service
metadata:
  name: ${APP}-blue
spec:
  type: LoadBalancer
  selector:
    app: ${APP}
    deployment: green 
  ports:
  - port: 80
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${APP}-${DEPLOYMENT}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ${APP}
        deployment: ${DEPLOYMENT}
    spec:
      containers:
      - name: ${APP}
        image: ${IMAGE}:${IMAGE_TAG}
        ports:
        - containerPort: 80
        readinessProbe:
           tcpSocket:
              port: 80
